site_name: Android TV on PC
site_url: https://androidtvonpc.github.io
theme:
  name: material
  palette:
      scheme: slate
      primary: green
      accent: deep orange
  font:
    text: DM Sans
    code: Fira Code
  logo: assets/androidtvonpclogo.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/git-alt
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.footer
    - content.code.copy
    - navigation.tracking
    - navigation.indexes
    - toc.integrate
nav:
  - Home: index.md
  - 'Getting Started': getting-started.md
  - 'Setup and Installation': 
    - 'Making the Bootable Drive': Setup and Installation/making-the-bootable-drive.md
    - 'Making the Internal Drive': Setup and Installation/making-the-internal-drive.md
  - 'Setting up your new system':
    - 'Initial OOBE Setup': Setting up your new system/Initial-OOBE-setup.md
    - 'Recommended Apps': Setting up your new system/recommended-apps.md
  - 'Maintenance and Updates': maintenanceupdates.md
  - 'Project Makers and Contributors': project-makers.md

  


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ddosintruders/AndroidTVonPC
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/adnan-r-ahmed
    - icon: fontawesome/solid/globe
      link: https://adnan-ahmed.pages.dev
    - icon: fontawesome/solid/envelope
      link: mailto:adnanclever78@gmail.com
    - icon: simple/kofi
      link: https://ko-fi.com/ddosintruders


copyright: Copyright &copy; 2026 Adnan Ahmed. All rights reserved.
repo_url: https://github.com/ddosintruders/AndroidTVonPC
repo_name: AndroidTVonPC

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true